on:
  push:
    branches:
      - main
name: 🚀 Deploy RealEstate360 website on push
jobs:
  web-deploy:
    name: 🎉 Deploy RealEstate360 Livesite Server
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: topchordrealty.techbasecomputersolutions.com
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        server-dir: /
        exclude: |
          **/.git*
          **/.git*/**
          **/application/cache/**
          **/application/config/database.php
          **/.buildpath/**
          .ftp-deploy-sync-state.json
          .git-ftp.log
          .htaccess
          .project
